# Generated by Django 3.2.16 on 2022-12-29 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('prj', '0004_auto_20221228_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Ratings',
            field=models.ManyToManyField(blank=True, related_name='rating', to=settings.STAR_RATINGS_RATING_MODEL, verbose_name='ستاره ها'),
        ),
    ]
